server:
  port: 8010
mybatis:
  configuration:
    mapper-locations: classpath:mapper/*.xml
    #开启驼峰命名规则
    map-underscore-to-camel-case: true
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  datasource:
      url: "jdbc:mysql://localhost:3306/crud?characterEncoding=UTF-8&serverTimezone=UTC"
      username: 'root'
      password: '1234'
      driver-class-name: com.mysql.jdbc.Driver
    #      type: com.alibaba.druid.pool.DruidDataSource

    #数据源
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
# 连接池最大连接数（使用负值表示没有限制）
    jedis.pool.max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool:
    max-wait: -1
# 连接池中的最大空闲连接
    jedis.pool.max-idle: 8
# 连接池中的最小空闲连接
    jedis.pool.min-idle: 0
# 连接超时时间（毫秒）
    timeout: 5000
#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#    converters:
#      preferred-json-mapper:




